version: '2.1'

services:
    zoo1:
        image: zookeeper:3.4.9
        hostname: zoo1
        ports:
            - "2181:2181"
        environment:
            ZOO_MY_ID: 1
            ZOO_PORT: 2181
            ZOO_SERVERS: server.1=zoo1:2888:3888
        volumes:
            - ./zoo1/data:/data
            - ./zoo1/datalog/:/datalog

    kafka:
        image: confluentinc/cp-kafka:5.0.1
        hostname: kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092, LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
            KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
            KAFKA_BROKER_ID: 1
            KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.aysnc.DefaultEventHandler=INFO,state.change.logger=INFO"
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        volumes:
            - ./kafka/data:/var/lib/kafka/data
        depends_on:
            - zoo1

    log-generator:
        image: orhanbalci/log-generator:latest
        hostname: log-generator
        volumes:
            - ./logs:/opt/app/logs

    log-pusher:
        image: orhanbalci/log-pusher:latest
        hostname: log-pusher
        environment:
            KAFKA_SERVER: "kafka:19092"
        volumes:
            - ./logs:/opt/app/logs
        depends_on:
            - kafka

    log-db:
        image: orhanbalci/log-db:latest
        hostname: log-db
        ports:
            - "5432:5432"

    log-puller:
        hostname: log-puller
        image: orhanbalci/log-puller:latest
        environment:
            KAFKA_SERVER: "kafka:19092"
            POSTGRES_URL: "jdbc:postgresql://log-db:5432/log_db"
        depends_on:
            - kafka
